#+TITLE: TOGridPile

Goal is a system of stacking cups whose dimensions
are multiples of 1+1/2" or 1/2" (to fit with my gridbeam stuff)
and that can, at least in some cases, fit into baseplates/lower cups
even when rotated around the X or Y axes (Z being up).

** Versions

X-rounded means X radius curves.

Shape versions:
- v0.0 :: 3/16" radius rounded 1.5" cube
- v0.1 :: 1/8" beveled 1.5" cube
- v1 :: Same as v2 but with vertical corners always rounded 3/8"
- v2 :: 1/8" beveled cube except faces have a 1/16"-rounding
- v3 :: same as v2 plus a straight-sided 'column', an extruded 1/16"-rounded 1/8*0.707" beveled 1+1/4" square
- v4 :: Compatible with v3 baseplates but with the column only along the center of each edge
  - Sits less securely than v3 or v5
- v5 :: Compatible with v3 baseplates but with the column only in the corners
- v6 :: Compatible with v3 baseplates but with the column around each 1/2" block
- v6.1 :: Smaller column bevels (so thicker columns) than v6 due to fixing some math; perhaps not useful
- v6.2 :: Larger column bevels (so narrower columns) to accomodate columns diagonally between the columns, similar to v8.4
- v7 :: An experimental simplification based on 3/16"-rounded cubes + 1/8"-rounded 3/8" columns
  - See TGx7.scad
- v8 :: Further simplification, based on 1/2" spherical atoms with 3/8" cylindrical columns,
  closely approximating the shape of v6 blocks.
  While a v8 block is 'smaler' than a v6 block,
  with v8 blocks fittiong loosely into v3, v5, v6 baseplates,
  with margins taken into account, v5/v6 blocks snap snugly into v8 baseplates, too.
- v8.4 :: Slice off corners of columns so that, as with v6.2, another could fit between them diagonally
- v9 :: A new design based on extruding along a path, similar to gridfinity, intended to be easier for OpenSCAD to handle
  and make make pieces that are more aesthetically pleasing (thickness of walls being consistent around corners,
  no weird jagged bits, etc), generally compatible with earlier versions.
- v9.0 :: Both male and female shapes use 1/4" / 3/16" (outer and for the column) radius corners
- v9.1 :: Female shape uses 3/16" / 1/4" radius corners,
  making it able to accept v3..v6 blocks, but v9.1 blocks won't fit sideways into v3 or their own base plates.

Current recommendation:
- female (subtract from baseplates/lips) :: v6 or v6.1
- male (blocks/feet) :: v6, v6.2, or v8.4

*** Notes

- As of [2023-05-29], I am wondering how the 0.707 multiplier for the bevel was chosen.
  ~0.707 = cos(pi/4), or 1/sqrt(2)~ and is used to calculate the offset from the corners
  where circles of which we take the hull are placed, but that is taken into account
  by ~togridpile__xy_rounded_beveled_square~, and yet ~inset*2*0.707~
  (where inset is the inset from the edge of the block to the column, usually 1/16")
  is passed to that function (v3-v6 all do this).
  It may have been to make the beveledness more closely match that
  of the outer hull, but I don't remember exactly how it was calculated.
